Controllers/TripsController.cs
using G4.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace G4.Controllers
{
    public class TripsController : Controller
    {
        private readonly PRN211Context _context;

        public TripsController(PRN211Context context)
        {
            _context = context;
        }

        // GET: Trips
        public async Task<IActionResult> Index()
        {
            var pRN211Context = _context.Trips.Include(t => t.Route.End).Include(t => t.Wagon.Class).Include(t => t.Route.Start).Include(t => t.Route).Include(t => t.Wagon).Include(t => t.Wagon.Train);
            return View(await pRN211Context.ToListAsync());
        }

        // GET: Trips/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Trips == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .Include(t => t.Route)
                .Include(t => t.Wagon)
                .FirstOrDefaultAsync(m => m.TripId == id);
            if (trip == null)
            {
                return NotFound();
            }


            return View(trip);
        }

        // GET: Trips/Create
        public IActionResult Create(int? wagonId, int? routeId, DateTime? date)
        {
            if (wagonId == null || routeId == null || date == null)
            {
                wagonId = _context.Wagons.FirstOrDefault().WagonId;
                routeId = _context.RouteTrains.FirstOrDefault().RouteId;
                date = date ?? DateTime.UtcNow;
            }
            var existingSlots = _context.Trips
            .Where(s => s.WagonId == wagonId && s.RouteId == routeId)
            .Select(s => s.Slot)
            .Distinct()
            .ToList();
            var validSlots = Enumerable.Range(1, 12).Select(s => (int?)s).Except(existingSlots).ToList();

            ViewData["Slot"] = new SelectList(validSlots);
            ViewData["RouteId"] = new SelectList(_context.RouteTrains, "RouteId", "RouteId");
            ViewData["WagonId"] = new SelectList(_context.Wagons, "WagonId", "WagonId");
            return View();
        }

        // POST: Trips/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TripId,Slot,WagonId,Price,Date,RouteId,Status")] Trip trip)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trip);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RouteId"] = new SelectList(_context.RouteTrains, "RouteId", "RouteId", trip.RouteId);
            ViewData["WagonId"] = new SelectList(_context.Wagons, "WagonId", "WagonId", trip.WagonId);
            return View(trip);
        }

        // GET: Trips/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trips == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips.FindAsync(id);
            if (trip == null)
            {
                return NotFound();
            }
            int? wagonId = trip.WagonId;
            int? routeId = trip.RouteId;
            if (wagonId == null || routeId == null)
            {

                wagonId = _context.Wagons.FirstOrDefault().WagonId;
                routeId = _context.RouteTrains.FirstOrDefault().RouteId;
            }
            var existingSlots = _context.Trips
                .Where(s => s.TripId != id && s.WagonId == wagonId && s.RouteId == routeId && s.Date == trip.Date)
                .Select(s => s.Slot)
                .Distinct()
                .ToList();

            var validSlots = Enumerable.Range(1, 12).Select(s => (int?)s).Except(existingSlots).ToList();

            ViewData["Slot"] = new SelectList(validSlots);
            ViewData["Wagon"] = new SelectList(_context.Wagons, "WagonId", "Name", wagonId);
            ViewData["Route"] = new SelectList(_context.RouteTrains, "RouteId", "RouteId", routeId);

            return View(trip);
        }
        [HttpGet]
        public IActionResult GetAvailableSlots(int wagonId, int routeId, DateTime date)
        {
            var existingSlots = _context.Trips
                .Where(s => s.WagonId == wagonId && s.RouteId == routeId && s.Date == date)
                .Select(s => s.Slot)
                .Distinct()
                .ToList();
            var validSlots = Enumerable.Range(1, 12).Select(s => (int?)s).Except(existingSlots).ToList();

            return Json(validSlots);
        }

        // POST: Trips/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TripId,Slot,WagonId,Price,Date,RouteId,Status")] Trip trip)
        {
            if (id != trip.TripId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var tripBefore = _context.Trips
                        .Include(t => t.Wagon)
                        .Include(t => t.Route)
                        .FirstOrDefault(s => s.TripId == id);
                    tripBefore.Slot = trip.Slot;
                    tripBefore.Price = trip.Price;
                    tripBefore.RouteId = trip.RouteId;

                    var routeTrain = _context.RouteTrains
                        .FirstOrDefault(r => r.RouteId == tripBefore.RouteId);
                    if (routeTrain != null)
                    {
                        tripBefore.Route = routeTrain;
                    }
                    _context.Update(tripBefore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TripExists(trip.TripId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RouteId"] = new SelectList(_context.RouteTrains, "RouteId", "RouteId", trip.RouteId);
            ViewData["WagonId"] = new SelectList(_context.Wagons, "WagonId", "WagonId", trip.WagonId);
            return View(trip);
        }

        // GET: Trips/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trips == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .Include(t => t.Route)
                .Include(t => t.Wagon)
                .FirstOrDefaultAsync(m => m.TripId == id);
            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // POST: Trips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trips == null)
            {
                return Problem("Entity set 'PRN211Context.Trips'  is null.");
            }
            var trip = await _context.Trips.FindAsync(id);
            if (trip != null)
            {
                _context.Trips.Remove(trip);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TripExists(int id)
        {
            return (_context.Trips?.Any(e => e.TripId == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - G4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/G4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">G4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            @{Account a = new Account();}
                            @{if ( a.GetAccountStatus)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            }
                            }
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trips" asp-action="Index">Trips</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - G4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>